### ISSUE TITLE
Can't build the qoi package with Python 3.12

### ISSUE THREAD

**Issue by gudnimg** [kodonnell/qoi#18]
Note numpy 1.26 is needed with Python 3.12 because distutils is removed.
```
Building wheels for collected packages: qoi
  Building wheel for qoi (pyproject.toml): started
  Building wheel for qoi (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  Building wheel for qoi (pyproject.toml) did not run successfully.
  exit code: 1

  [50 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-312
  creating build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\benchmark.py -> build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\_version.py -> build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\__init__.py -> build\lib.win-amd64-cpython-312\qoi
  copying src\qoi\qoi.pxd -> build\lib.win-amd64-cpython-312\qoi
  running build_ext
  building 'qoi.qoi' extension
  creating build\temp.win-amd64-cpython-312
  creating build\temp.win-amd64-cpython-312\Release
  creating build\temp.win-amd64-cpython-312\Release\src
  creating build\temp.win-amd64-cpython-312\Release\src\qoi
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DQOI_MALLOC=PyMem_Malloc -DQOI_FREE=PyMem_Free -IC:\Users\Gudni\AppData\Local\Temp\pip-build-env-c92eykgi\overlay\Lib\site-packages\numpy\core\include -ID:\Prusa-Firmware-Buddy-Private\.venv\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/qoi/implementation.c /Fobuild\temp.win-amd64-cpython-312\Release\src/qoi/implementation.obj
  implementation.c
  C:\Users\Gudni\AppData\Local\Temp\pip-install-y6f4ym_p\qoi_7194dc5fc5904c6d98e093ad731ed32d\src\qoi\phoboslab_qoi/qoi.h(597): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  C:\Users\Gudni\AppData\Local\Temp\pip-install-y6f4ym_p\qoi_7194dc5fc5904c6d98e093ad731ed32d\src\qoi\phoboslab_qoi/qoi.h(641): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
  C:\Users\Gudni\AppData\Local\Temp\pip-install-y6f4ym_p\qoi_7194dc5fc5904c6d98e093ad731ed32d\src\qoi\phoboslab_qoi/qoi.h(619): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DQOI_MALLOC=PyMem_Malloc -DQOI_FREE=PyMem_Free -IC:\Users\Gudni\AppData\Local\Temp\pip-build-env-c92eykgi\overlay\Lib\site-packages\numpy\core\include -ID:\Prusa-Firmware-Buddy-Private\.venv\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\include -IC:\Users\Gudni\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/qoi/qoi.c /Fobuild\temp.win-amd64-cpython-312\Release\src/qoi/qoi.obj
  qoi.c
  C:\Users\Gudni\AppData\Local\Temp\pip-build-env-c92eykgi\overlay\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  src/qoi/qoi.c(13239): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
  src/qoi/qoi.c(21985): error C2039: 'curexc_traceback': is not a member of '_ts'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
  src/qoi/qoi.c(21988): error C2039: 'curexc_traceback': is not a member of '_ts'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/pystate.h(115): note: see declaration of '_ts'
  src/qoi/qoi.c(23336): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(24904): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(24959): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25100): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25155): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25296): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25351): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25530): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25585): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  src/qoi/qoi.c(25936): error C2039: 'ob_digit': is not a member of '_longobject'
  C:\Users\Gudni\AppData\Local\Programs\Python\Python312\include\cpython/longintrepr.h(87): note: see declaration of '_longobject'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qoi
Failed to build qoi
ERROR: Could not build wheels for qoi, which is required to install pyproject.toml-based projects
```

**Comment by synodriver** [comment]
It seems that py312 changed the internal structure of ```PyLongObject```. Do you have Cython installed? Try run ```$env:USE_CYTHON=1``` before compile and see that would happen.

**Comment by synodriver** [comment]
@kodonnell Should we update CI to provide prebuild wheels for python3.11 and 3.12? They didn't exists on [PyPi](https://pypi.org/project/qoi/0.3.1/#files).

**Comment by gudnimg** [comment]
The problem goes away with Python 3.11.7. At least on my end this is only a problem with 3.12.

**Comment by synodriver** [comment]
How did you build with 3.12? poetry or setup.py?

**Comment by gudnimg** [comment]
I think its setup.py

I had installed a fresh 3.12 (upgrading from 3.11) on Windows 11 and ran `pip install qoi`, I didnt install poetry

I have a requirements.txt and feed that to pip

**Comment by synodriver** [comment]
Try git clone and build?

**Comment by kodonnell** [comment]
Sorry I was looking into this without realising you both were working on it = )

> @kodonnell Should we update CI to provide prebuild wheels for python3.11 and 3.12? They didn't exists on [PyPi](https://pypi.org/project/qoi/0.3.1/#files).

Yes. I was just updating the cibuildwheels to run for 3.12 and that's where I noticed it failed (on linux too). I then created a new conda env with 3.12.0  (on linux) and while everything builds properly, it segfaults:

![image](https://github.com/kodonnell/qoi/assets/8204904/0255a28d-cd97-43ae-a937-b7c3c8e96c2f)

I'm a bit out of my depth here. I had a quick squiz and it looks like 3.12 meant a big change for scipy etc. I'd started porting across their updated pyproject.toml before running into this.

**Comment by kodonnell** [comment]
I just pushed branch py312 which had my progress if that's useful. Nothing major in there though.

**Comment by gudnimg** [comment]
> Try git clone and build?

I have little experience in this area, but I will try and report back.

**Comment by gudnimg** [comment]
Just to add more information, I was using Python 3.12.1, not sure if it behaves different from 3.12.0

**Comment by synodriver** [comment]
I‘m testing it on windows in a conda environment. It build succefully, but when running tests, I just got
```
(py312) PS E:\pyproject\qoi\src> pytest .\test_qoi.py
================================================================================= test session starts =================================================================================
platform win32 -- Python 3.12.0, pytest-7.4.3, pluggy-1.3.0
rootdir: E:\pyproject\qoi
collected 27 items

test_qoi.py Windows fatal exception: access violation

Current thread 0x000328e0 (most recent call first):
  File "E:\pyproject\qoi\src\test_qoi.py", line 23 in test_write_read
  File "D:\conda\envs\py312\Lib\site-packages\_pytest\python.py", line 194 in pytest_pyfunc_call
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_callers.py", line 77 in _multicall
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_manager.py", line 115 in _hookexec
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_hooks.py", line 493 in __call__
  File "D:\conda\envs\py312\Lib\site-packages\_pytest\python.py", line 1792 in runtest
  File "D:\conda\envs\py312\Lib\site-packages\_pytest\runner.py", line 169 in pytest_runtest_call
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_callers.py", line 77 in _multicall
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_manager.py", line 115 in _hookexec
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_hooks.py", line 493 in __call__
  File "D:\conda\envs\py312\Lib\site-packages\_pytest\main.py", line 318 in pytest_cmdline_main
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_callers.py", line 77 in _multicall
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_manager.py", line 115 in _hookexec
  File "D:\conda\envs\py312\Lib\site-packages\pluggy\_hooks.py", line 493 in __call__
  File "D:\conda\envs\py312\Lib\site-packages\_pytest\config\__init__.py", line 169 in main
  File "D:\conda\envs\py312\Lib\site-packages\_pytest\config\__init__.py", line 192 in console_main
  File "D:\conda\envs\py312\Scripts\pytest.exe\__main__.py", line 7 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main
```
I think this is a bug related to cython

**Comment by synodriver** [comment]
By inserting a lot of printf, I found the segfault was introduced in the underlying C library api call. Sounds strange. I'll dig deeper to see the real reason.

**Comment by synodriver** [comment]
Got it, ```QOI_MALLOC``` caused this problem, in this case, ```PyMem_Malloc```... Strange error.
![image](https://github.com/kodonnell/qoi/assets/50922489/8cacb4dc-2ecc-4d64-806e-75c3ef1d36ba)

**Comment by synodriver** [comment]
So, the question is: what's wrong with PyMem_Malloc in python3.12

**Comment by gudnimg** [comment]
@synodriver thanks for looking into this!

The bug you found, does it explain the build error I saw?

> error C2039: 'curexc_traceback': is not a member of '_ts'

Is it just a consequence of the malloc call failing? I’m wondering if you could reproduce the same error message as I was getting.

**Comment by synodriver** [comment]
> @synodriver thanks for looking into this!
> 
> The bug you found, does it explain the build error I saw?
> 
> > error C2039: 'curexc_traceback': is not a member of '_ts'
> > error C2039: 'ob_digit': is not a member of '_longobject'
> 
> Is it just a consequence of the malloc call failing? I’m wondering if you could reproduce the same error message as I was getting.

I'll build on Debian again to see what happens

**Comment by synodriver** [comment]
@gudnimg Your problem seems related to Cython, did you tried update your cython version? I'm not able to reproduce your problem on Debian, 
```
uname -a
Linux Gallibrary 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
```
![image](https://github.com/kodonnell/qoi/assets/50922489/072c2b5f-e594-4dea-9888-422ae354ed59)
I got not error, no warnings on my server

**Comment by gudnimg** [comment]
@synodriver no I haven't touched Cython, I'm using whatever is default with the Python 3.12.1 installation.

I'll re-install 3.12.1 again this evening and re-test this and also check my Cython version.

**Comment by gudnimg** [comment]
@synodriver just for reference, are you testing on latest main + https://github.com/kodonnell/qoi/pull/19? Maybe the Cython upgrade in https://github.com/kodonnell/qoi/pull/17 fixed things.

**Comment by synodriver** [comment]
![image](https://github.com/kodonnell/qoi/assets/50922489/1d55bb5b-1414-4604-b825-32f207da3f78)

That's why you are not able to build using pip. The bundled qoi.c is too old for python3.12, and need to regenerate with cython3.0.6

**Comment by synodriver** [comment]
[qoi-0.0.0-cp312-cp312-linux_x86_64.zip](https://github.com/kodonnell/qoi/files/13627507/qoi-0.0.0-cp312-cp312-linux_x86_64.zip)
If you need it now, try this prebuild wheel

**Comment by gudnimg** [comment]
I'm back on a fresh 3.12.1 installation on Windows 11

I've added `USE_CYTHON=1` to Windows' Environment Variables and I build the `qoi` package using `python -m build` in the top directory (where `.toml` file is)

I then install the package like this: `pip install "D:\qoi\dist\qoi-0.3.2.dev6+g9d55cb9.d20231210.tar.gz"` and it seems to work.

* Build successful: Using latest main branch + https://github.com/kodonnell/qoi/commits/py312
* Build successful: Using latest main branch
* Build fails: Switching back to f5a0ba206911fff04132c1ef4e7fb6ac8e542223 and the build fails as expected

When I remove `USE_CYTHON=1`, installing the qoi package still works 👍

**Comment by kodonnell** [comment]
Thanks a lot both - good solving. I'll push a new version to pypi tonight with all the changes.

**Comment by kodonnell** [comment]
0.4.0 released!

**Comment by gudnimg** [comment]
`pip install qoi` works like a charm with Python 3.12.1 🙏

**Comment by synodriver** [comment]
I've found another mistake, maybe we should release a new version for that:(...... To completely eliminate such bugs, I made a few branch ```DEBUG```, hoping to catch memory issues.

**Comment by synodriver** [comment]
Valgrind didn't detect any ```definitely lost``` block,  the latest main should be fine.
