### ISSUE TITLE
Can't build with numpy 2.2

### ISSUE THREAD

**Issue by wavexx** [kodonnell/qoi#32]
I recently updated my build env to python 3.13 and numpy 2.2.2, and getting the following build error:

```
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -O3 -flto -march=native -pipe -fPIC -DQOI_MALLOC=PyMem_RawMalloc -DQOI_FREE=PyMem_RawFree -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/usr/lib/x86_64-linux-gnu/python3-numpy/numpy/_core/include -I/usr/include/python3.13 -c src/qoi/qoi.c -o build/temp.linux-x86_64-cpython-313/src/qoi/qoi.o
In file included from /usr/include/python3.13/Python.h:63,
                 from src/qoi/qoi.c:49:
src/qoi/qoi.c: In function ‘__pyx_f_5numpy_PyDataType_SHAPE’:
src/qoi/qoi.c:18849:39: error: ‘PyArray_Descr’ {aka ‘struct _PyArray_Descr’} has no member named ‘subarray’
18849 |     __Pyx_INCREF(((PyObject*)__pyx_v_d->subarray->shape));
      |                                       ^~
```

**Comment by kodonnell** [comment]
Sounds similar to https://github.com/TA-Lib/ta-lib-python/pull/656 - I'm not entirely sure what's going on. We specifically request >2 though as per https://github.com/kodonnell/qoi/blob/ecf244143f862df5801daadbe1d2260bb1ef3075/pyproject.toml#L15 ... just copying how scipy did it. @synodriver has been good at this stuff previously, so may be able to comment?

**Comment by wavexx** [comment]
I was able to fix the build by explicitly setting USE_CYTHON, not sure if that's intended...

**Comment by kodonnell** [comment]
Ah that makes sense, though a bit of an unhelpful error message = ) Yes you need `USE_CYTHON` as per the readme - the reason comes from https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules So it's possible there was an old .c file lying around, or maybe there's still a bug here. I'll close for now though as it seems to be resolved, but will leave it to be reopened if someone else notices it.
